-- This is an SQL script to create authorised values for the IELD Koha
-- database.
-- Run it with a command like this:
-- $ mysql koha_ield < authorised_values.sql

DELETE FROM authorised_values
WHERE category="COUNTRY"
OR category="CCODE";

INSERT INTO authorised_values
(category, authorised_value, lib, lib_opac)
VALUES
("CCODE","0 - General works","0 - General works",NULL),
("CCODE","1 - Philosophy","1 - Philosophy",NULL),
("CCODE","2 - Religion","2 - Religion",NULL),
("CCODE","3 - Social Sciences","3 - Social Sciences",NULL),
("CCODE","4 - Language","4 - Language",NULL),
("CCODE","5 - Pure Sciences","5 - Pure Sciences",NULL),
("CCODE","6 - Applied Sciences","6 - Applied Sciences",NULL),
("CCODE","7 - Arts & Recreations","7 - Arts & Recreations",NULL),
("CCODE","8 - Literature","8 - Literature",NULL),
("CCODE","9 - History","9 - History",NULL),
("CCODE","Biography","Biography",NULL),
("CCODE","Biography Collection","Biography Collection",NULL),
("CCODE","Course Book","Course Book",NULL),
("CCODE","Detective Stories","Detective Stories",NULL),
("CCODE","Easy Readers","Easy Readers",NULL),
("CCODE","Fiction","Fiction",NULL),
("CCODE","Graphic Books","Graphic Books",NULL),
("CCODE","Juvenile Fiction","Juvenile Fiction",NULL),
("CCODE","Juvenile Non-Fiction","Juvenile Non-Fiction",NULL),
("CCODE","Reference","Reference",NULL),
("CCODE","Science Fiction","Science Fiction",NULL),
("CCODE","Short Stories","Short Stories",NULL),
("CCODE","Short-Story Collection","Short-Story Collection",NULL),
("CCODE","TESL","TESL",NULL),
("CCODE","Travel","Travel",NULL);

INSERT INTO authorised_values
(category, authorised_value, lib, lib_opac)
VALUES
("COUNTRY","Abkhazia","Abkhazia",NULL),
("COUNTRY","Afghanistan","Afghanistan",NULL),
("COUNTRY","Albania","Albania",NULL),
("COUNTRY","Algeria","Algeria",NULL),
("COUNTRY","Andorra","Andorra",NULL),
("COUNTRY","Angola","Angola",NULL),
("COUNTRY","Antigua and Barbuda","Antigua and Barbuda",NULL),
("COUNTRY","Argentina","Argentina",NULL),
("COUNTRY","Armenia","Armenia",NULL),
("COUNTRY","Australia","Australia",NULL),
("COUNTRY","Austria","Austria",NULL),
("COUNTRY","Azerbaijan","Azerbaijan",NULL),
("COUNTRY","Bahamas","Bahamas",NULL),
("COUNTRY","Bahrain","Bahrain",NULL),
("COUNTRY","Bangladesh","Bangladesh",NULL),
("COUNTRY","Barbados","Barbados",NULL),
("COUNTRY","Belarus","Belarus",NULL),
("COUNTRY","Belgium","Belgium",NULL),
("COUNTRY","Belize","Belize",NULL),
("COUNTRY","Benin","Benin",NULL),
("COUNTRY","Bhutan","Bhutan",NULL),
("COUNTRY","Bolivia","Bolivia",NULL),
("COUNTRY","Bosnia and Herzegovina","Bosnia and Herzegovina",NULL),
("COUNTRY","Botswana","Botswana",NULL),
("COUNTRY","Brazil","Brazil",NULL),
("COUNTRY","Brunei","Brunei",NULL),
("COUNTRY","Bulgaria","Bulgaria",NULL),
("COUNTRY","Burkina Faso","Burkina Faso",NULL),
("COUNTRY","Burundi","Burundi",NULL),
("COUNTRY","Cabo Verde","Cabo Verde",NULL),
("COUNTRY","Cambodia","Cambodia",NULL),
("COUNTRY","Cameroon","Cameroon",NULL),
("COUNTRY","Canada","Canada",NULL),
("COUNTRY","Central African Republic","Central African Republic",NULL),
("COUNTRY","Chad","Chad",NULL),
("COUNTRY","Chile","Chile",NULL),
("COUNTRY","China","China",NULL),
("COUNTRY","Colombia","Colombia",NULL),
("COUNTRY","Comoros","Comoros",NULL),
("COUNTRY","Congo, Republic of the","Congo, Republic of the",NULL),
("COUNTRY","Congo, Democratic Republic of the","Congo, Democratic Republic of the",NULL),
("COUNTRY","Cook Islands","Cook Islands",NULL),
("COUNTRY","Costa Rica","Costa Rica",NULL),
("COUNTRY","Cote d'Ivoire","Cote d'Ivoire",NULL),
("COUNTRY","Croatia","Croatia",NULL),
("COUNTRY","Cuba","Cuba",NULL),
("COUNTRY","Cyprus","Cyprus",NULL),
("COUNTRY","Czech Republic","Czech Republic",NULL),
("COUNTRY","Denmark","Denmark",NULL),
("COUNTRY","Djibouti","Djibouti",NULL),
("COUNTRY","Dominica","Dominica",NULL),
("COUNTRY","Dominican Republic","Dominican Republic",NULL),
("COUNTRY","Ecuador","Ecuador",NULL),
("COUNTRY","Egypt","Egypt",NULL),
("COUNTRY","El Salvador","El Salvador",NULL),
("COUNTRY","Equatorial Guinea","Equatorial Guinea",NULL),
("COUNTRY","Eritrea","Eritrea",NULL),
("COUNTRY","Estonia","Estonia",NULL),
("COUNTRY","Ethiopia","Ethiopia",NULL),
("COUNTRY","Fiji","Fiji",NULL),
("COUNTRY","Finland","Finland",NULL),
("COUNTRY","France","France",NULL),
("COUNTRY","Gabon","Gabon",NULL),
("COUNTRY","Gambia","Gambia",NULL),
("COUNTRY","Georgia","Georgia",NULL),
("COUNTRY","Germany","Germany",NULL),
("COUNTRY","Ghana","Ghana",NULL),
("COUNTRY","Greece","Greece",NULL),
("COUNTRY","Grenada","Grenada",NULL),
("COUNTRY","Guatemala","Guatemala",NULL),
("COUNTRY","Guinea","Guinea",NULL),
("COUNTRY","Guinea-Bissau","Guinea-Bissau",NULL),
("COUNTRY","Guyana","Guyana",NULL),
("COUNTRY","Haiti","Haiti",NULL),
("COUNTRY","Honduras","Honduras",NULL),
("COUNTRY","Hungary","Hungary",NULL),
("COUNTRY","Iceland","Iceland",NULL),
("COUNTRY","India","India",NULL),
("COUNTRY","Indonesia","Indonesia",NULL),
("COUNTRY","Iran","Iran",NULL),
("COUNTRY","Iraq","Iraq",NULL),
("COUNTRY","Ireland","Ireland",NULL),
("COUNTRY","Israel","Israel",NULL),
("COUNTRY","Italy","Italy",NULL),
("COUNTRY","Jamaica","Jamaica",NULL),
("COUNTRY","Japan","Japan",NULL),
("COUNTRY","Jordan","Jordan",NULL),
("COUNTRY","Kazakhstan","Kazakhstan",NULL),
("COUNTRY","Kenya","Kenya",NULL),
("COUNTRY","Kiribati","Kiribati",NULL),
("COUNTRY","Kosovo","Kosovo",NULL),
("COUNTRY","Kuwait","Kuwait",NULL),
("COUNTRY","Kyrgyzstan","Kyrgyzstan",NULL),
("COUNTRY","Laos","Laos",NULL),
("COUNTRY","Latvia","Latvia",NULL),
("COUNTRY","Lebanon","Lebanon",NULL),
("COUNTRY","Lesotho","Lesotho",NULL),
("COUNTRY","Liberia","Liberia",NULL),
("COUNTRY","Libya","Libya",NULL),
("COUNTRY","Liechtenstein","Liechtenstein",NULL),
("COUNTRY","Lithuania","Lithuania",NULL),
("COUNTRY","Luxembourg","Luxembourg",NULL),
("COUNTRY","Macedonia","Macedonia",NULL),
("COUNTRY","Madagascar","Madagascar",NULL),
("COUNTRY","Malawi","Malawi",NULL),
("COUNTRY","Malaysia","Malaysia",NULL),
("COUNTRY","Maldives","Maldives",NULL),
("COUNTRY","Mali","Mali",NULL),
("COUNTRY","Malta","Malta",NULL),
("COUNTRY","Marshall Islands","Marshall Islands",NULL),
("COUNTRY","Mauritania","Mauritania",NULL),
("COUNTRY","Mauritius","Mauritius",NULL),
("COUNTRY","Mexico","Mexico",NULL),
("COUNTRY","Micronesia","Micronesia",NULL),
("COUNTRY","Moldova","Moldova",NULL),
("COUNTRY","Monaco","Monaco",NULL),
("COUNTRY","Mongolia","Mongolia",NULL),
("COUNTRY","Montenegro","Montenegro",NULL),
("COUNTRY","Morocco","Morocco",NULL),
("COUNTRY","Mozambique","Mozambique",NULL),
("COUNTRY","Myanmar (Burma)","Myanmar (Burma)",NULL),
("COUNTRY","Namibia","Namibia",NULL),
("COUNTRY","Nauru","Nauru",NULL),
("COUNTRY","Nepal","Nepal",NULL),
("COUNTRY","Netherlands","Netherlands",NULL),
("COUNTRY","New Zealand","New Zealand",NULL),
("COUNTRY","Nicaragua","Nicaragua",NULL),
("COUNTRY","Niger","Niger",NULL),
("COUNTRY","Nigeria","Nigeria",NULL),
("COUNTRY","Niue","Niue",NULL),
("COUNTRY","North Korea","North Korea",NULL),
("COUNTRY","Norway","Norway",NULL),
("COUNTRY","Oman","Oman",NULL),
("COUNTRY","Pakistan","Pakistan",NULL),
("COUNTRY","Palau","Palau",NULL),
("COUNTRY","Palestine","Palestine",NULL),
("COUNTRY","Panama","Panama",NULL),
("COUNTRY","Papua New Guinea","Papua New Guinea",NULL),
("COUNTRY","Paraguay","Paraguay",NULL),
("COUNTRY","Peru","Peru",NULL),
("COUNTRY","Philippines","Philippines",NULL),
("COUNTRY","Poland","Poland",NULL),
("COUNTRY","Portugal","Portugal",NULL),
("COUNTRY","Qatar","Qatar",NULL),
("COUNTRY","Romania","Romania",NULL),
("COUNTRY","Russia","Russia",NULL),
("COUNTRY","Rwanda","Rwanda",NULL),
("COUNTRY","St. Kitts and Nevis","St. Kitts and Nevis",NULL),
("COUNTRY","St. Lucia","St. Lucia",NULL),
("COUNTRY","St. Vincent and The Grenadines","St. Vincent and The Grenadines",NULL),
("COUNTRY","Samoa","Samoa",NULL),
("COUNTRY","San Marino","San Marino",NULL),
("COUNTRY","Sao Tome and Principe","Sao Tome and Principe",NULL),
("COUNTRY","Saudi Arabia","Saudi Arabia",NULL),
("COUNTRY","Senegal","Senegal",NULL),
("COUNTRY","Serbia","Serbia",NULL),
("COUNTRY","Seychelles","Seychelles",NULL),
("COUNTRY","Sierra Leone","Sierra Leone",NULL),
("COUNTRY","Singapore","Singapore",NULL),
("COUNTRY","Slovakia","Slovakia",NULL),
("COUNTRY","Slovenia","Slovenia",NULL),
("COUNTRY","Solomon Islands","Solomon Islands",NULL),
("COUNTRY","Somalia","Somalia",NULL),
("COUNTRY","South Africa","South Africa",NULL),
("COUNTRY","South Korea","South Korea",NULL),
("COUNTRY","South Sudan","South Sudan",NULL),
("COUNTRY","Spain","Spain",NULL),
("COUNTRY","Sri Lanka","Sri Lanka",NULL),
("COUNTRY","Sudan","Sudan",NULL),
("COUNTRY","Suriname","Suriname",NULL),
("COUNTRY","Swaziland","Swaziland",NULL),
("COUNTRY","Sweden","Sweden",NULL),
("COUNTRY","Switzerland","Switzerland",NULL),
("COUNTRY","Syria","Syria",NULL),
("COUNTRY","Taiwan","Taiwan",NULL),
("COUNTRY","Tajikistan","Tajikistan",NULL),
("COUNTRY","Tanzania","Tanzania",NULL),
("COUNTRY","Thailand","Thailand",NULL),
("COUNTRY","Timor-Leste","Timor-Leste",NULL),
("COUNTRY","Togo","Togo",NULL),
("COUNTRY","Tonga","Tonga",NULL),
("COUNTRY","Trinidad and Tobago","Trinidad and Tobago",NULL),
("COUNTRY","Tunisia","Tunisia",NULL),
("COUNTRY","Turkey","Turkey",NULL),
("COUNTRY","Turkmenistan","Turkmenistan",NULL),
("COUNTRY","Tuvalu","Tuvalu",NULL),
("COUNTRY","Uganda","Uganda",NULL),
("COUNTRY","Ukraine","Ukraine",NULL),
("COUNTRY","United Arab Emirates","United Arab Emirates",NULL),
("COUNTRY","United Kingdom","United Kingdom",NULL),
("COUNTRY","United States of America","United States of America",NULL),
("COUNTRY","Uruguay","Uruguay",NULL),
("COUNTRY","Uzbekistan","Uzbekistan",NULL),
("COUNTRY","Vanuatu","Vanuatu",NULL),
("COUNTRY","Vatican City","Vatican City",NULL),
("COUNTRY","Venezuela","Venezuela",NULL),
("COUNTRY","Vietnam","Vietnam",NULL),
("COUNTRY","Yemen","Yemen",NULL),
("COUNTRY","Zambia","Zambia",NULL),
("COUNTRY","Zimbabwe","Zimbabwe",NULL);

